name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git config
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Bot"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      # - name: Run linter
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     yarn lint

      # - name: Run tests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     yarn test

      - name: Run build
        run: |
          yarn build:client
